### ISSUE TITLE
`hatchet install` when specifying `main` for the first time on a new resource fails.

### ISSUE THREAD

**Issue by schneems** [heroku/hatchet#117]
```
git clone https://github.com/heroku/heroku-buildpack-nodejs
git co shared-hatchet-tests
```

```
$ bundle exec hatchet install
Installing repos for hatchet
error: could not apply 2f5a0b5... add readme
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 2f5a0b5... add readme
bundler: failed to load command: hatchet (/Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet)
RuntimeError: Command cd /Users/rschneeman/Documents/projects/all_buildpacks/heroku-buildpack-nodejs/repos/heroku/node-js-getting-started && git pull --rebase https://github.com/heroku/node-js-getting-started.git --quiet failed:
CONFLICT (add/add): Merge conflict in README.md
Auto-merging README.md

  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-7.0.0/bin/hatchet:176:in `cmd'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-7.0.0/bin/hatchet:162:in `pull'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-7.0.0/bin/hatchet:51:in `block (2 levels) in install'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/threaded-0.0.4/lib/threaded.rb:73:in `block in later'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/threaded-0.0.4/lib/threaded/promise.rb:34:in `block in call'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/threaded-0.0.4/lib/threaded/promise.rb:29:in `synchronize'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/threaded-0.0.4/lib/threaded/promise.rb:29:in `call'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/threaded-0.0.4/lib/threaded/promise.rb:62:in `wait_for_it!'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/threaded-0.0.4/lib/threaded/promise.rb:46:in `now'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-7.0.0/bin/hatchet:62:in `map'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-7.0.0/bin/hatchet:62:in `install'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-7.0.0/bin/hatchet:181:in `<top (required)>'
  /Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet:23:in `load'
  /Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet:23:in `<top (required)>'
```

This is because `cd /Users/rschneeman/Documents/projects/all_buildpacks/heroku-buildpack-nodejs/repos/heroku/node-js-getting-started` is empty, so when you try to rebase, it traverses up until it hits the top level git directory of the buildpack repo instead.

**Comment by schneems** [comment]
This only happens when you specify a different branch than what github has as the default branch.
