### ISSUE TITLE
Hatchet destroy "NoMethodError: undefined method `destroy_by_name'"

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#143]
Using heroku_hatchet 7.3.0:

```
$ bundle exec hatchet destroy --help
 ›   Warning: token will expire 08/10/2021
 ›   Use heroku authorizations:create to generate a long-term token
bundler: failed to load command: hatchet (/usr/local/lib/ruby/gems/2.7.0/bin/hatchet)
NoMethodError: undefined method `destroy_by_name' for #<Hatchet::Reaper:0x00007fc52095d7f0>
Did you mean?  destroy_all
  /usr/local/lib/ruby/gems/2.7.0/gems/heroku_hatchet-7.3.0/bin/hatchet:120:in `destroy'
  /usr/local/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/local/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /usr/local/lib/ruby/gems/2.7.0/gems/heroku_hatchet-7.3.0/bin/hatchet:192:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.7.0/bin/hatchet:23:in `load'
  /usr/local/lib/ruby/gems/2.7.0/bin/hatchet:23:in `<top (required)>'
```

The destroy command references `destroy_by_name` here:
https://github.com/heroku/hatchet/blob/7dc0726ba8b91e776435aecbc91d8f2f5ac8e56d/bin/hatchet#L120

But this was removed in:
https://github.com/heroku/hatchet/commit/329ffb5c32310180c14ad3bc51bb25b2b02793d5#diff-13e1288d09b3addeddccd4f98f12479dL53

**Comment by edmorley** [comment]
Fixed by d0a96b04a99bfb9f70443447dd8fbcd41b53f917
