### ISSUE TITLE
Support and test against Ruby 3

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#159]
Currently running `hatchet --help` using Ruby 3.0.0 fails with:

```
/usr/local/lib/ruby/gems/3.0.0/gems/heroics-0.1.1/lib/heroics.rb:7:in `require': cannot load such file -- webrick (LoadError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/heroics-0.1.1/lib/heroics.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/platform-api-3.2.0/lib/platform-api.rb:1:in `require'
	from /usr/local/lib/ruby/gems/3.0.0/gems/platform-api-3.2.0/lib/platform-api.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:3:in `require'
	from /usr/local/lib/ruby/gems/3.0.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/heroku_hatchet-7.3.3/lib/hatchet.rb:16:in `require'
	from /usr/local/lib/ruby/gems/3.0.0/gems/heroku_hatchet-7.3.3/lib/hatchet.rb:16:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/heroku_hatchet-7.3.3/bin/hatchet:13:in `require'
	from /usr/local/lib/ruby/gems/3.0.0/gems/heroku_hatchet-7.3.3/bin/hatchet:13:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/hatchet:23:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/hatchet:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
	from /usr/local/opt/ruby/bin/bundle:23:in `load'
	from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
```

That will be fixed by interagent/heroics/pull/101 once merged/released, however:
* there may be other fixes required
* it would be good to add Ruby 3 to the hatchet CI versions matrix

**Comment by schneems** [comment]
I've merged and released that PR for heroics v0.1.2. I'm 👍 on adding Ruby 3.0 to the test matrix.

Long term we need to migrate heroics to circle-ci as well as getting it tested on Ruby 3.0 as well

**Comment by edmorley** [comment]
Thank you :-)
