### ISSUE TITLE
CI failing on main in ci_spec.rb after default stack change

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#173]
The Circle CI run is failing on `main` with:

```
Failures:

  1) CIFourTest error with bad app
     Failure/Error:
       expect {
         Hatchet::GitApp.new("rails5_ci_fails_no_database").run_ci { }
       }.to raise_error(/PG::ConnectionBad: could not connect to server/)
     
       expected /PG::ConnectionBad: could not connect to server/, got #<Hatchet::FailedTestError: Could not run tests on pipeline id: '7d61bf24-f0cf-490b-9d74-5ec543b32b5d...or declaring a Ruby version see:
        !     https://devcenter.heroku.com/articles/ruby-versions
        !
       > with backtrace:
         # ./lib/hatchet/test_run.rb:135:in `block in wait!'
         # ./lib/hatchet/test_run.rb:127:in `wait!'
         # ./lib/hatchet/app.rb:485:in `block in run_ci'
         # ./lib/hatchet/app.rb:377:in `block (2 levels) in in_directory'
         # ./lib/hatchet/app.rb:375:in `chdir'
         # ./lib/hatchet/app.rb:375:in `block in in_directory'
         # ./lib/hatchet/app.rb:373:in `in_directory'
         # ./lib/hatchet/app.rb:457:in `run_ci'
         # ./spec/hatchet/ci_spec.rb:31:in `block (3 levels) in <top (required)>'
         # ./spec/hatchet/ci_spec.rb:30:in `block (2 levels) in <top (required)>'
         # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
         # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
         # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
         # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
         # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/command_line.rb:29:in `block in run'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:507:in `call_with_index'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:477:in `process_incoming_jobs'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:459:in `block in worker'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `fork'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `worker'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:441:in `block in create_workers'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each_with_index'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `create_workers'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:380:in `work_in_processes'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:283:in `map'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:228:in `in_processes'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/command_line.rb:23:in `run'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:13:in `block in run'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:23:in `report_execution_time'
         # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:12:in `run'
     # ./spec/hatchet/ci_spec.rb:30:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/command_line.rb:29:in `block in run'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:507:in `call_with_index'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:477:in `process_incoming_jobs'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:459:in `block in worker'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `fork'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `worker'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:441:in `block in create_workers'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each_with_index'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `create_workers'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:380:in `work_in_processes'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:283:in `map'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:228:in `in_processes'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/command_line.rb:23:in `run'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:13:in `block in run'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:23:in `report_execution_time'
     # ./vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:12:in `run'

Finished in 48.5 seconds (files took 1.34 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/hatchet/ci_spec.rb:29 # CIFourTest error with bad app
```

This is because the fixture specifies Ruby 2.4.1 in its `Gemfile.lock`:
https://github.com/sharpstone/rails5_ci_fails_no_database/blob/3044f05febdfbbe656f0f5113cf5968ca07e34fd/Gemfile.lock#L158

...but that version does not exist for Heroku-20:
https://devcenter.heroku.com/articles/ruby-support#oldest-available-runtimes

The options are:
1. Make this test use the `heroku-18` stack (like it was before the default stack changed to Heroku-20)
2. Update the fixture repo to use Ruby 2.5.8+

It seems like it might be worth doing (1) in this repo as a stop-gap, even if (2) is desirable longer term.

**Comment by edmorley** [comment]
Opened #174 to resolve this.
