### ISSUE TITLE
Hatchet not detecting rate limit being hit in some cases

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#176]
I just got a failure due to hitting the rate limit, where the response from the Git server mentions the rate limit:

> error: RPC failed; HTTP 429 curl 22 The requested URL returned error: 429

...but that wording is not in the list that Hatchet recognises:
https://github.com/heroku/hatchet/blob/7dc0726ba8b91e776435aecbc91d8f2f5ac8e56d/lib/hatchet/git_app.rb#L16

As such I believe Hatchet retried and didn't use the rate limiting behaviour.

@schneems Have I interpreted the logs correctly?

Full log:

```
Retrying failed Attempt #1/3 to push for 'hatchet-t-1380b55fc6' due to error: 
Hatchet::App::FailedDeployError Could not deploy 'hatchet-t-1380b55fc6' (spec/fixtures/python_3.9_outdated) using 'Hatchet::GitApp' at path: 'spec/fixtures/python_3.9_outdated'
if this was expected add `allow_failure: true` to your deploy hash.
Buildpack: nil
Repo: https://git.heroku.com/hatchet-t-1380b55fc6.git
output:
error: RPC failed; HTTP 429 curl 22 The requested URL returned error: 429
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/git_app.rb:36:in `git_push_heroku_yall'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/git_app.rb:13:in `block in push_without_retry!'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/shell_throttle.rb:28:in `block (2 levels) in call'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/shell_throttle.rb:27:in `catch'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/shell_throttle.rb:27:in `block in call'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rate_throttle_client-0.1.2/lib/rate_throttle_client/clients/exponential_increase_proportional_remaining_decrease.rb:17:in `call'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/shell_throttle.rb:26:in `call'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/git_app.rb:11:in `push_without_retry!'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:425:in `block in push'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rrrretry-1.0.0/lib/rrrretry.rb:41:in `retry'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:423:in `push'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:413:in `block (2 levels) in deploy'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:100:in `annotate_failures'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:411:in `block in deploy'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:377:in `block (2 levels) in in_directory'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:375:in `chdir'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:375:in `block in in_directory'
  /home/travis/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:373:in `in_directory'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/heroku_hatchet-7.3.3/lib/hatchet/app.rb:410:in `deploy'
  /home/travis/build/heroku/heroku-buildpack-python/spec/hatchet/python_update_warning_spec.rb:7:in `block (2 levels) in <top (required)>'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/command_line.rb:29:in `block in run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:507:in `call_with_index'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:477:in `process_incoming_jobs'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:459:in `block in worker'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `fork'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `worker'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:441:in `block in create_workers'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each_with_index'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `create_workers'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:380:in `work_in_processes'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:283:in `map'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:228:in `in_processes'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/command_line.rb:23:in `run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:13:in `block in run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:23:in `report_execution_time'
  /home/travis/build/heroku/hero
ku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:12:in `run'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/gems/parallel_split_test-0.9.0/bin/parallel_split_test:25:in `<top (required)>'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/bin/parallel_split_test:23:in `load'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/bin/parallel_split_test:23:in `<main>'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `eval'
  /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by edmorley** [comment]
Another variation not being detected:

```
Failures:

  1) AppTest run multi
     Failure/Error: raise FailedDeployError.new(self, "Buildpack: #{@buildpack.inspect}\nRepo: #{git_repo}", output: output)
     
     Hatchet::App::FailedDeployError:
       Could not deploy 'hatchet-t-43f4b7bcac' (default_ruby) using 'Hatchet::GitApp' at path: 'repo_fixtures/repos/default/default_ruby'
       if this was expected add `allow_failure: true` to your deploy hash.
       Buildpack: nil
       Repo: https://git.heroku.com/hatchet-t-43f4b7bcac.git
       output:
       error: RPC failed; result=22, HTTP code = 429
       fatal: The remote end hung up unexpectedly
       fatal: The remote end hung up unexpectedly
       Everything up-to-date
     # ./lib/hatchet/git_app.rb:36:in `git_push_heroku_yall'
     # ./lib/hatchet/git_app.rb:13:in `block in push_without_retry!'
     # ./lib/hatchet/shell_throttle.rb:28:in `block (2 levels) in call'
     # ./lib/hatchet/shell_throttle.rb:27:in `catch'
     # ./lib/hatchet/shell_throttle.rb:27:in `block in call'
     # ./vendor/bundle/ruby/2.2.0/gems/rate_throttle_client-0.1.2/lib/rate_throttle_client/clients/exponential_increase_proportional_remaining_decrease.rb:17:in `call'
     # ./lib/hatchet/shell_throttle.rb:26:in `call'
     # ./lib/hatchet/git_app.rb:11:in `push_without_retry!'
     # ./lib/hatchet/app.rb:425:in `block in push'
     # ./vendor/bundle/ruby/2.2.0/gems/rrrretry-1.0.0/lib/rrrretry.rb:41:in `retry'
     # ./lib/hatchet/app.rb:423:in `push'
     # ./lib/hatchet/app.rb:413:in `block (2 levels) in deploy'
     # ./lib/hatchet/app.rb:100:in `annotate_failures'
     # ./lib/hatchet/app.rb:411:in `block in deploy'
     # ./lib/hatchet/app.rb:377:in `block (2 levels) in in_directory'
     # ./lib/hatchet/app.rb:375:in `chdir'
     # ./lib/hatchet/app.rb:375:in `block in in_directory'
     # ./lib/hatchet/app.rb:373:in `in_directory'
     # ./lib/hatchet/app.rb:410:in `deploy'
     # ./spec/hatchet/app_spec.rb:248:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/command_line.rb:29:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:508:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:508:in `call_with_index'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:472:in `process_incoming_jobs'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:454:in `block in worker'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:445:in `fork'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:445:in `worker'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:436:in `block in create_workers'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `each'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `each_with_index'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `create_workers'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:374:in `work_in_processes'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:278:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel-1.19.2/lib/parallel.rb:224:in `in_processes'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/command_line.rb:23:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:13:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:23:in `report_execution_time'
     # ./vendor/bundle/ruby/2.2.0/gems/parallel_split_test-0.9.0/lib/parallel_split_test/runner.rb:12:in `run'
     # ------------------
     # --- Caused by: ---
     # StopIteration:
     #   iteration reached an end
     #   ./vendor/bundle/ruby/2.2.0/gems/rrrretry-1.0.0/lib/rrrretry.rb:34:in `next'
```

**Comment by edmorley** [comment]
> Another variation not being detected (from the Hatchet repo's own test suite):

Second occurrence of this type in:
https://app.circleci.com/pipelines/github/heroku/hatchet/302/workflows/8c926c3c-5044-42c4-972f-13741acfc571/jobs/884

**Comment by schneems** [comment]
The regex we're looking for is:

```
          when /reached the API rate limit/, /429 Too Many Requests/
```

Which doesn't match

```
error: RPC failed; HTTP 429 curl 22 The requested URL returned error: 429
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
```
or

```
       error: RPC failed; result=22, HTTP code = 429
       fatal: The remote end hung up unexpectedly
       fatal: The remote end hung up unexpectedly
```

It's a little frustrating that this case isn't better normalized.
